import { createReproductionEcologyRuntimeV1 } from "../../KGEN-KAIOS/world-viewer/ecosystem/ecosystem-runtime.js";

const view=document.getElementById("view"),status=document.getElementById("status"),errorBox=document.getElementById("error"),errorDetail=document.getElementById("error-detail");
let runtime;let activeView="map";let timer=null;
const number=(value,digits=1)=>Number(value??0).toFixed(digits);const text=(value)=>String(value??"");
function card(title,rows,meter=null){const article=document.createElement("article");article.className="card";const heading=document.createElement("h3");heading.textContent=title;const dl=document.createElement("dl");for(const [key,value] of rows){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=key;dd.textContent=text(value);dl.append(dt,dd)}article.append(heading,dl);if(meter!==null){const bar=document.createElement("div"),fill=document.createElement("span");bar.className="meter";fill.style.width=`${Math.max(0,Math.min(100,meter))}%`;bar.append(fill);article.append(bar)}return article}
function renderMap(state){const fragment=document.createDocumentFragment(),conditions=document.createElement("div"),map=document.createElement("div");conditions.className="conditions";for(const condition of state.conditions.length?state.conditions:["BALANCED_BASELINE"]){const tag=document.createElement("span");tag.textContent=condition;conditions.append(tag)}map.className="map";for(const habitat of state.habitats){const populations=state.populations.filter(({habitat_id})=>habitat_id===habitat.id).reduce((sum,item)=>sum+item.count,0);map.append(card(habitat.type,[["Water",`${number(habitat.water_l)} L`],["Temperature",`${number(habitat.temperature_c)} C`],["Oxygen",`${number(habitat.oxygen_mg_l)} mg/L`],["Pollution",number(habitat.pollution,2)],["Population",populations],["Restoration",habitat.restoration_state]]))}fragment.append(conditions,map);return fragment}
function render(){const state=runtime.getState(),integrity=runtime.integrityReport();document.getElementById("runtime-state").textContent=state.status;document.getElementById("tick").textContent=state.simulation_time;document.getElementById("population-total").textContent=`${integrity.total_biological_population} / ${integrity.maximum_total_population}`;document.getElementById("condition-count").textContent=state.conditions.length;status.textContent=`${state.status} · ${integrity.ok?"Integrity PASS":"Integrity FAIL"}`;view.setAttribute("aria-busy","false");view.replaceChildren();
  if(activeView==="map")view.append(renderMap(state));
  if(activeView==="habitats"){const grid=document.createElement("div");grid.className="grid";state.habitats.forEach((h)=>grid.append(card(h.type,[["Habitat ID",h.id],["Area",`${number(h.area_m2,0)} m2`],["Water",`${number(h.water_l)} L`],["Oxygen",number(h.oxygen_mg_l)],["Soil fertility",number(h.soil_fertility,2)],["Authority",h.authority]])));view.append(grid)}
  if(activeView==="populations"||activeView==="capacity"){const grid=document.createElement("div");grid.className="grid";state.populations.forEach((p)=>grid.append(card(p.species_id.replace("SPECIES-KAIOS-FOUNDATIONAL-",""),[["Population ID",p.population_id],["Count",p.count],["Capacity",p.carrying_capacity],["Status",p.population_status],["Generation",p.generation],["Reproduction",p.reproduction_modes.join(" / ")]],p.carrying_capacity?p.count/p.carrying_capacity*100:0)));view.append(grid)}
  if(activeView==="food"){const grid=document.createElement("div");grid.className="grid";[["Plant producers","GRASS / TREE → PLANT_BIOMASS"],["Aquatic food","ABSTRACT_RESOURCE_POOL → FISH / SHRIMP"],["Detritus","DETRITUS_POOL → SHRIMP"],["Material return","DEAD_BIOMASS → DECOMPOSITION → SOIL_NUTRIENTS"],["Water dependency","WATER → GRASS / TREE / FISH / SHRIMP"],["Runoff","MOUNTAIN → RIVER → HABITAT"]].forEach(([name,flow])=>grid.append(card(name,[["Flow",flow],["Mode","MASS_TRANSFER_REQUIRED"],["Authority","SIMULATION_ONLY"]])));view.append(grid)}
  if(activeView==="resources"){const grid=document.createElement("div");grid.className="grid";Object.entries(state.resources).forEach(([key,value])=>grid.append(card(key,[["Current",number(value,3)],["Accounting","BOUNDED_LEDGER"],["Negative allowed","false"]])));view.append(grid)}
  if(activeView==="events"){const list=document.createElement("ol");list.className="timeline";const events=state.events.slice(-120).reverse();if(!events.length){const li=document.createElement("li");li.textContent="No events yet.";list.append(li)}for(const event of events){const li=document.createElement("li"),tick=document.createElement("span"),typeNode=document.createElement("strong"),reason=document.createElement("span");tick.textContent=`T${event.simulation_time}`;typeNode.textContent=event.type;reason.textContent=`${event.reason} · ${event.next_state_hash}`;li.append(tick,typeNode,reason);list.append(li)}view.append(list)}
}
function boot(){try{pauseTimer();runtime=createReproductionEcologyRuntimeV1();runtime.createEcosystem();runtime.pause();errorBox.hidden=true;render()}catch(error){errorDetail.textContent=error instanceof Error?error.message:"Unknown error";errorBox.hidden=false;status.textContent="LOAD_FAILED"}}
function pauseTimer(){if(timer)clearInterval(timer);timer=null;if(runtime)runtime.pause()}
function runTimer(){pauseTimer();runtime.resume();timer=setInterval(advance,1800);render()}
function advance(){if(runtime.getState().status!=="RUNNING")runtime.resume();runtime.advanceTime(1);render()}
function download(){const blob=new Blob([JSON.stringify(runtime.exportState(),null,2)],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="kaios-ecosystem-v1-simulation.json";link.click();URL.revokeObjectURL(link.href)}
document.querySelectorAll(".tabs button").forEach((button)=>button.addEventListener("click",()=>{document.querySelectorAll(".tabs button").forEach((item)=>item.classList.remove("active"));button.classList.add("active");activeView=button.dataset.view;render()}));
document.getElementById("start").addEventListener("click",runTimer);document.getElementById("pause").addEventListener("click",()=>{pauseTimer();render()});document.getElementById("resume").addEventListener("click",runTimer);document.getElementById("advance").addEventListener("click",advance);document.getElementById("reset").addEventListener("click",()=>{pauseTimer();runtime.resetState();runtime.pause();render()});document.getElementById("export").addEventListener("click",download);document.getElementById("retry").addEventListener("click",boot);
document.getElementById("run-scenario").addEventListener("click",()=>{const scenario=document.getElementById("scenario").value;runtime.resume();if(scenario==="DROUGHT")runtime.processDrought({water_l:28000,habitat_factor:0.25});if(scenario==="POLLUTION")runtime.processPollution(0.62);if(scenario==="RESTORATION")runtime.processRestoration({water_l:18000,nutrients_kg:80,pollution_reduction:0.4});runtime.advanceTime(1);runtime.pause();render()});
document.getElementById("import").addEventListener("change",async(event)=>{const [file]=event.target.files;if(!file)return;try{pauseTimer();runtime.importState(JSON.parse(await file.text()));render();errorBox.hidden=true}catch(error){errorDetail.textContent=error instanceof Error?error.message:"Invalid import";errorBox.hidden=false}finally{event.target.value=""}});
boot();
