import { createFoundationalLifeRuntime } from "../../KAIOS/life/runtime/foundational-life-runtime.js";
import { loadFoundationalLifeDefinitions } from "../../KAIOS/life/runtime/foundational-life-loader.js";

const grid=document.getElementById("life-grid"), eventList=document.getElementById("event-list"), status=document.getElementById("runtime-status"), tickCount=document.getElementById("tick-count"), errorState=document.getElementById("error-state"), errorDetail=document.getElementById("error-detail"), speedSelect=document.getElementById("speed-select");
let runtime=null, timer=null;
const controls=["start-button","pause-button","step-button","replay-button","reset-button","export-button","import-input","speed-select"].map((id)=>document.getElementById(id));
const metric=(value)=>value===null?"N/A":Number(value).toFixed(2);
const setControlsDisabled=(disabled)=>controls.forEach((control)=>{control.disabled=disabled;});
const summarize=(value)=>{if(value===null||value===undefined)return "N/A";if(typeof value==="string"||typeof value==="number"||typeof value==="boolean")return String(value);if(Array.isArray(value))return value.slice(0,3).map(summarize).join(", ");return Object.entries(value).slice(0,3).map(([key,item])=>`${key}: ${summarize(item)}`).join("; ");};

function createCard(state){ const card=document.createElement("article"); card.className="life-card"; card.dataset.state=state.life_state; const progressName=state.growth_progress===null?"Formation":"Growth", progressValue=state.growth_progress??state.formation_progress??0; const taxonomy=state.taxonomy?.extension_19??state.taxonomy??{}; card.innerHTML=`<header><h3></h3><span></span></header><dl><dt>Life ID</dt><dd class="life-id"></dd><dt>Species ID</dt><dd class="species-id"></dd><dt>Life Type</dt><dd class="life-type"></dd><dt>Taxonomy</dt><dd class="taxonomy"></dd><dt>Environment</dt><dd class="environment"></dd><dt>State</dt><dd class="life-state"></dd><dt>Health / Integrity</dt><dd>${metric(state.health)} / ${metric(state.integrity)}</dd><dt>Energy / Water</dt><dd>${metric(state.energy)} / ${metric(state.water_balance)}</dd><dt>Age</dt><dd>${metric(state.age_days)} days</dd><dt>Location</dt><dd class="location"></dd><dt>${progressName}</dt><dd>${metric(progressValue)}% <progress max="100" value="${progressValue}">${progressValue}</progress></dd><dt>Needs</dt><dd class="needs"></dd><dt>Economic Role</dt><dd class="economy"></dd><dt>Rights</dt><dd class="rights"></dd><dt>Runtime</dt><dd class="runtime-status"></dd><dt>Approval</dt><dd class="approval"></dd><dt>Events</dt><dd>${state.event_history.length}</dd></dl>`; card.querySelector("h3").textContent=state.display_name; card.querySelector("header span").textContent=state.package_name.toUpperCase(); card.querySelector(".life-id").textContent=state.life_id; card.querySelector(".species-id").textContent=state.species_id; card.querySelector(".life-type").textContent=state.life_type; card.querySelector(".taxonomy").textContent=`${taxonomy.Kingdom??taxonomy.KINGDOM??"N/A"} / ${taxonomy.Species??taxonomy.SPECIES??state.species_id}`; card.querySelector(".environment").textContent=summarize(state.environment); card.querySelector(".life-state").textContent=state.life_state; card.querySelector(".location").textContent=summarize(state.location); card.querySelector(".needs").textContent=summarize(state.traits?.resource_inputs); card.querySelector(".economy").textContent=summarize(state.economic_role?.market_role??state.economic_role); card.querySelector(".rights").textContent=`${Object.keys(state.rights??{}).length} separated classes`; card.querySelector(".runtime-status").textContent=state.runtime_status; card.querySelector(".approval").textContent=state.approval_status.join(" / "); return card; }
function render(){ const states=runtime.listStates(); grid.replaceChildren(...states.map(createCard)); grid.setAttribute("aria-busy","false"); const events=states.flatMap(({event_history})=>event_history).sort((a,b)=>b.event_id.localeCompare(a.event_id)).slice(0,80); if(!events.length){ const empty=document.createElement("li"); empty.textContent="No events yet."; eventList.replaceChildren(empty); } else eventList.replaceChildren(...events.map((event)=>{ const item=document.createElement("li"), tick=document.createElement("span"), name=document.createElement("strong"), detail=document.createElement("span"); tick.textContent=`T${event.simulation_time}`; name.textContent=event.package_name.toUpperCase(); detail.textContent=event.reason?`${event.status}: ${event.reason}`:event.type; item.append(tick,name,detail); return item; })); tickCount.textContent=`Tick ${Math.max(...states.map(({tick})=>tick))}`; status.textContent=timer?"Running locally":"Paused locally"; }
function step(){const wasRunning=runtime.isRunning();if(!wasRunning)runtime.resume();runtime.tickAll();if(!wasRunning)runtime.pause();render();} function pause(){ if(timer)clearInterval(timer); timer=null; if(runtime){runtime.pause();render();} } function start(){ if(timer)clearInterval(timer); runtime.resume(); timer=setInterval(step,Number(speedSelect.value)); render(); }
function downloadState(){ const blob=new Blob([JSON.stringify(runtime.exportSimulation(),null,2)],{type:"application/json"}), link=document.createElement("a"); link.href=URL.createObjectURL(blob); link.download="kaios-life-runtime-v1-simulation.json"; link.click(); URL.revokeObjectURL(link.href); }
async function boot(){ if(runtime)pause(); runtime=null; setControlsDisabled(true); errorState.hidden=true; grid.setAttribute("aria-busy","true"); status.textContent="Loading candidate definitions..."; try{ runtime=createFoundationalLifeRuntime({definitions:await loadFoundationalLifeDefinitions()}); runtime.pause(); setControlsDisabled(false); render(); }catch(error){ grid.setAttribute("aria-busy","false"); errorDetail.textContent=error instanceof Error?error.message:"Unknown load error"; errorState.hidden=false; status.textContent="Load failed"; } }
document.getElementById("start-button").addEventListener("click",start); document.getElementById("pause-button").addEventListener("click",pause); document.getElementById("step-button").addEventListener("click",step); document.getElementById("reset-button").addEventListener("click",()=>{pause();runtime.reset();runtime.pause();render();}); document.getElementById("replay-button").addEventListener("click",()=>{pause();runtime.resume();runtime.replay();runtime.pause();render();}); document.getElementById("export-button").addEventListener("click",downloadState); document.getElementById("retry-button").addEventListener("click",boot); speedSelect.addEventListener("change",()=>{if(timer)start();});
document.getElementById("import-input").addEventListener("change",async(event)=>{ const [file]=event.target.files; if(!file)return; pause(); try{runtime.importSimulation(JSON.parse(await file.text()));render();}catch(error){errorDetail.textContent=error instanceof Error?error.message:"Invalid import";errorState.hidden=false;}finally{event.target.value="";} });
setControlsDisabled(true);
boot();
