import { createFoundationalLifeRuntime } from "../../KAIOS/life/runtime/foundational-life-runtime.js";
import { loadFoundationalLifeDefinitions } from "../../KAIOS/life/runtime/foundational-life-loader.js";

const grid=document.getElementById("life-grid"), eventList=document.getElementById("event-list"), status=document.getElementById("runtime-status"), tickCount=document.getElementById("tick-count"), errorState=document.getElementById("error-state"), errorDetail=document.getElementById("error-detail"), speedSelect=document.getElementById("speed-select");
let runtime=null, timer=null;
const controls=["start-button","pause-button","step-button","replay-button","reset-button","export-button","import-input","speed-select"].map((id)=>document.getElementById(id));
const metric=(value)=>value===null?"N/A":Number(value).toFixed(2);
const setControlsDisabled=(disabled)=>controls.forEach((control)=>{control.disabled=disabled;});

function createCard(state){ const card=document.createElement("article"); card.className="life-card"; card.dataset.state=state.life_state; const progressName=state.growth_progress===null?"Formation":"Growth", progressValue=state.growth_progress??state.formation_progress??0; card.innerHTML=`<header><h3></h3><span></span></header><dl><dt>Life ID</dt><dd class="life-id"></dd><dt>State</dt><dd class="life-state"></dd><dt>Health</dt><dd>${metric(state.health)}</dd><dt>Integrity</dt><dd>${metric(state.integrity)}</dd><dt>Energy</dt><dd>${metric(state.energy)}</dd><dt>Water balance</dt><dd>${metric(state.water_balance)}</dd><dt>${progressName}</dt><dd>${metric(progressValue)}%</dd><dt>Progress</dt><dd><progress max="100" value="${progressValue}">${progressValue}</progress></dd><dt>Events</dt><dd>${state.event_history.length}</dd></dl>`; card.querySelector("h3").textContent=state.display_name; card.querySelector("header span").textContent=state.package_name.toUpperCase(); card.querySelector(".life-id").textContent=state.life_id; card.querySelector(".life-state").textContent=state.life_state; return card; }
function render(){ const states=runtime.listStates(); grid.replaceChildren(...states.map(createCard)); grid.setAttribute("aria-busy","false"); const events=states.flatMap(({event_history})=>event_history).sort((a,b)=>b.event_id.localeCompare(a.event_id)).slice(0,80); if(!events.length){ const empty=document.createElement("li"); empty.textContent="No events yet."; eventList.replaceChildren(empty); } else eventList.replaceChildren(...events.map((event)=>{ const item=document.createElement("li"), tick=document.createElement("span"), name=document.createElement("strong"), detail=document.createElement("span"); tick.textContent=`T${event.simulation_time}`; name.textContent=event.package_name.toUpperCase(); detail.textContent=event.reason?`${event.status}: ${event.reason}`:event.type; item.append(tick,name,detail); return item; })); tickCount.textContent=`Tick ${Math.max(...states.map(({tick})=>tick))}`; status.textContent=timer?"Running locally":"Paused locally"; }
function step(){ runtime.tickAll(); render(); } function pause(){ if(timer)clearInterval(timer); timer=null; if(runtime)render(); } function start(){ pause(); timer=setInterval(step,Number(speedSelect.value)); render(); }
function downloadState(){ const blob=new Blob([JSON.stringify(runtime.exportSimulation(),null,2)],{type:"application/json"}), link=document.createElement("a"); link.href=URL.createObjectURL(blob); link.download="kaios-life-runtime-v1-simulation.json"; link.click(); URL.revokeObjectURL(link.href); }
async function boot(){ pause(); runtime=null; setControlsDisabled(true); errorState.hidden=true; grid.setAttribute("aria-busy","true"); status.textContent="Loading candidate definitions..."; try{ runtime=createFoundationalLifeRuntime({definitions:await loadFoundationalLifeDefinitions()}); setControlsDisabled(false); render(); }catch(error){ grid.setAttribute("aria-busy","false"); errorDetail.textContent=error instanceof Error?error.message:"Unknown load error"; errorState.hidden=false; status.textContent="Load failed"; } }
document.getElementById("start-button").addEventListener("click",start); document.getElementById("pause-button").addEventListener("click",pause); document.getElementById("step-button").addEventListener("click",step); document.getElementById("reset-button").addEventListener("click",()=>{pause();runtime.reset();render();}); document.getElementById("replay-button").addEventListener("click",()=>{pause();runtime.replay();render();}); document.getElementById("export-button").addEventListener("click",downloadState); document.getElementById("retry-button").addEventListener("click",boot); speedSelect.addEventListener("change",()=>{if(timer)start();});
document.getElementById("import-input").addEventListener("change",async(event)=>{ const [file]=event.target.files; if(!file)return; pause(); try{runtime.importSimulation(JSON.parse(await file.text()));render();}catch(error){errorDetail.textContent=error instanceof Error?error.message:"Invalid import";errorState.hidden=false;}finally{event.target.value="";} });
setControlsDisabled(true);
boot();
