import test from 'node:test';
import assert from 'node:assert/strict';
import {AUDIO_STORAGE_KEY,AUDIO_THEMES,createKaiosAudio} from '../assets/kaios-audio.mjs';

function harness(saved){
  const data=new Map(saved?[[AUDIO_STORAGE_KEY,JSON.stringify(saved)]]:[]),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};
  const intervals=new Map(),timeouts=new Map();let next=0,contexts=[];
  class Param{value=0;events=[];cancelScheduledValues(){}setValueAtTime(value){this.value=value;this.events.push(['set',value]);}linearRampToValueAtTime(value){this.value=value;this.events.push(['ramp',value]);}exponentialRampToValueAtTime(value){this.value=value;}}
  class Node{gain=new Param();frequency=new Param();connect(){}disconnect(){this.disconnected=true;}start(){this.started=true;}stop(){this.stopped=true;}end(){this.onended?.();}}
  class Context{state='suspended';currentTime=1;destination={};osc=[];constructor(){contexts.push(this);}createGain(){return new Node();}createOscillator(){const node=new Node();this.osc.push(node);return node;}async resume(){this.state='running';}async suspend(){this.state='suspended';}async close(){this.state='closed';}}
  const doc=new EventTarget();doc.hidden=false;const env=new EventTarget();env.speechSynthesis={spoken:[],cancel(){this.cancelled=true;},getVoices:()=>[{lang:'zh-TW'}],speak(message){this.spoken.push(message);}};env.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};
  const audio=createKaiosAudio({env,document:doc,storage,AudioContext:Context,setInterval(fn){const id=++next;intervals.set(id,fn);return id;},clearInterval:id=>intervals.delete(id),setTimeout(fn){const id=++next;timeouts.set(id,fn);return id;},clearTimeout:id=>timeouts.delete(id)});
  return{audio,contexts,intervals,timeouts,doc,env,storage,data,finish(){for(const ctx of contexts)for(const node of ctx.osc)node.end();},async visibility(hidden){doc.hidden=hidden;doc.dispatchEvent(new Event('visibilitychange'));await Promise.resolve();await Promise.resolve();}};
}

test('silent default: no AudioContext, nodes, autoplay or voice before gesture',()=>{const h=harness();h.audio.setWorld('PORTAL');assert.equal(h.contexts.length,0);assert.equal(h.audio.play('BOSS_SPAWN'),false);assert.equal(h.audio.speak('hello'),false);assert.equal(h.audio.snapshot().musicPlaying,false);});
test('persisted enabled preference does not bypass new-document gesture',()=>{const h=harness({musicEnabled:true,muted:false});assert.equal(h.audio.snapshot().needsGesture,true);assert.equal(h.contexts.length,0);assert.equal(h.intervals.size,0);});
test('one context and one clock across repeated unlock/play calls',async()=>{const h=harness();await h.audio.unlock();await h.audio.unlock();h.audio.setMusicEnabled(true);h.audio.setMusicEnabled(true);assert.equal(h.contexts.length,1);assert.equal(h.intervals.size,1);assert.equal(h.audio.snapshot().activeMusicLayers,1);await h.audio.dispose();});
test('world identity plus bounded crossfade replaces scheduler, not a second player',async()=>{const h=harness();await h.audio.unlock();h.audio.setMusicEnabled(true);h.audio.setWorld('K12345');assert.equal(h.audio.snapshot().theme,AUDIO_THEMES['12345']);assert.equal(h.intervals.size,1);assert.equal(h.timeouts.size,1);h.audio.setWorld('16888');assert.equal(h.intervals.size,1);assert.equal(h.timeouts.size,1);assert.equal(h.contexts.length,1);await h.audio.dispose();assert.equal(h.timeouts.size,0);});
test('11520 original theme retains canonical motif and .34 second scheduling authority',async()=>{const h=harness();h.audio.setWorld('11520');await h.audio.unlock();h.audio.setMusicEnabled(true);const frequencies=h.contexts[0].osc.map(o=>o.frequency.events[0]?.[1]);assert(frequencies.includes(220));assert(frequencies.includes(55));assert(frequencies.includes(110));assert(frequencies.includes(92));await h.audio.dispose();});
test('mute stops clock and survives preference reload without enabling sound',async()=>{const h=harness();await h.audio.unlock();h.audio.setMusicEnabled(true);h.audio.setMuted(true);assert.equal(h.intervals.size,0);assert.equal(h.audio.play('HIT'),false);assert.equal(JSON.parse(h.data.get(AUDIO_STORAGE_KEY)).muted,true);h.audio.setMuted(false);assert.equal(h.intervals.size,1);await h.audio.dispose();});
test('volume channels clamp safely and reject unknown or nonfinite input',()=>{const h=harness();assert.equal(h.audio.setVolume('music',4),true);assert.equal(h.audio.snapshot().settings.music,1);assert.equal(h.audio.setVolume('voice',-.2),true);assert.equal(h.audio.setVolume('wallet',1),false);assert.equal(h.audio.setVolume('master',NaN),false);assert.equal(h.audio.snapshot().settings.voice,0);});
test('setting voice or master to zero immediately cancels owned speech',async()=>{for(const channel of ['voice','master']){const h=harness();await h.audio.unlock();h.audio.speak('說明');h.audio.setVolume(channel,0);assert.equal(h.env.speechSynthesis.cancelled,true);assert.equal(h.audio.speak('靜音時不得說話'),false);await h.audio.dispose();}});
test('voice uses shared master×voice gain and callbacks, mute cancels own speech',async()=>{const h=harness();await h.audio.unlock();h.audio.setVolume('master',.5);h.audio.setVolume('voice',.4);let ended=false;assert(h.audio.speak('取經開始',{onend:()=>{ended=true;}}));const voice=h.env.speechSynthesis.spoken[0];assert.equal(voice.volume,.2);assert.equal(voice.lang,'zh-TW');voice.onend();assert.equal(ended,true);h.audio.speak('再見');h.audio.setMuted(true);assert.equal(h.env.speechSynthesis.cancelled,true);await h.audio.dispose();});
test('visibility suspend/resume and repeated show produce exactly one scheduler',async()=>{const h=harness();await h.audio.unlock();h.audio.setMusicEnabled(true);await h.visibility(true);assert.equal(h.audio.snapshot().contextState,'suspended');assert.equal(h.intervals.size,0);assert.equal(h.audio.snapshot().activeNodes,0);await h.visibility(false);await h.visibility(false);assert.equal(h.intervals.size,1);assert.equal(h.audio.snapshot().contextState,'running');await h.audio.dispose();});
test('bounded SFX allocation and ended oscillator cleanup',async()=>{const h=harness();await h.audio.unlock();for(let i=0;i<200;i++)h.audio.tone({frequency:220});assert.equal(h.audio.snapshot().activeNodes,96);h.finish();assert.equal(h.audio.snapshot().activeNodes,0);await h.audio.dispose();});
test('all requested event identities play, repeat flood is throttled',async()=>{const h=harness();await h.audio.unlock();for(const key of ['BOSS_SPAWN','BOSS_PHASE_CHANGE','RARE_LOOT','PLAYER_LEVEL_UP','ENGINE_LEVEL_UP','HOME_BUILD','HOME_UPGRADE','PORTAL_OPEN','WORLD_ENTER','QUEST_COMPLETE']){assert.equal(h.audio.play(key),true,key);assert.equal(h.audio.play(key),false,key+' repeat');}assert.equal(h.audio.play('UNKNOWN'),false);await h.audio.dispose();});
test('storage unavailable is nonfatal and never loads secrets/assets',async()=>{const audio=createKaiosAudio({env:{},document:null,storage:{getItem(){throw new Error('blocked');},setItem(){throw new Error('blocked');}}});audio.setMuted(true);assert.equal(audio.snapshot().persistent,false);assert.equal(await audio.unlock(),false);assert.equal(audio.snapshot().lastError,'AUDIO_UNAVAILABLE');await audio.dispose();});
test('pagehide suspends sound; bfcache restore retains exactly one theme',async()=>{const h=harness();await h.audio.unlock();h.audio.setMusicEnabled(true);h.env.dispatchEvent(new Event('pagehide'));await Promise.resolve();assert.equal(h.intervals.size,0);assert.equal(h.audio.snapshot().activeNodes,0);const event=new Event('pageshow');event.persisted=true;h.env.dispatchEvent(event);await Promise.resolve();assert.equal(h.intervals.size,1);await h.audio.dispose();assert.equal(h.audio.snapshot().contextState,'closed');});
test('zero master/music and browser interruption never report music playing',async()=>{
 const h=harness();await h.audio.unlock();h.audio.setMusicEnabled(true);
 for(const channel of ['master','music']){h.audio.setVolume(channel,0);assert.equal(h.audio.snapshot().musicPlaying,false);h.audio.setVolume(channel,.65);assert.equal(h.audio.snapshot().musicPlaying,true);}
 h.contexts[0].state='interrupted';h.contexts[0].onstatechange();assert.equal(h.audio.snapshot().musicPlaying,false);assert.equal(h.audio.snapshot().needsGesture,true);assert.equal(h.intervals.size,0);
 // Chrome can implicitly resume before the click handler runs. Preserve the
 // visible recovery intent so that this first recovery tap does not mute again.
 h.contexts[0].state='running';h.contexts[0].onstatechange();assert.equal(h.audio.snapshot().needsGesture,true);assert.equal(h.intervals.size,0);
 await h.audio.unlock();assert.equal(h.intervals.size,1);assert.equal(h.audio.snapshot().musicPlaying,true);await h.audio.dispose();
});
test('mobile volume defaults do not overwrite saved low/zero volume or mute',()=>{const h=harness({master:0,music:.42,muted:true});assert.equal(h.audio.snapshot().settings.master,0);assert.equal(h.audio.snapshot().settings.music,.42);assert.equal(h.audio.snapshot().settings.muted,true);assert.equal(harness().audio.snapshot().settings.music,.65);});
