import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
const here=dirname(fileURLToPath(import.meta.url));
const html=readFileSync(resolve(here,'../game-5d.html'),'utf8');
const main=readFileSync(resolve(here,'../runtime/game-5d-main.mjs'),'utf8');
const bootstrap=readFileSync(resolve(here,'../runtime/game-5d-bootstrap.mjs'),'utf8');
const fixes=readFileSync(resolve(here,'../runtime/game-ui-product-fixes.mjs'),'utf8');
const organs=['world','trade','positions','orders','history','assets','records','market','bag','character','worldmap','atm','settings','help'];
const fixed=['three','lookPad','axes','walletPanel','walletToggle','walletConnect','walletRefresh','minimap','joy','knob','yControl','cControl','lotsControl','attack','skill','dodge','flat','orderFire','tradeSword','dock','dockToggle','rail','sheet','sheetClose','confirm','confirmOrder','cancelOrder','lifeDetails'];

test('product display is explicitly versioned as V2.3',()=>{assert.ok(html.includes('<title>11520 花果山 V2.3 · 5D K線西遊記</title>'));assert.ok(html.includes('11520 花果山 V2.3'));assert.ok(html.includes('5D K線西遊記'));assert.ok(fixes.includes('VERSION: 2.3.0'));assert.ok(bootstrap.includes('VERSION: 2.3.0'))});
test('Living Market HUD is compact-by-default and user-expandable',()=>{assert.ok(html.includes('<details id="lifeDetails">'));assert.ok(html.includes('<summary>Living Market · 點擊展開</summary>'));assert.ok(html.includes('details[open] #monsterList'))});
test('all formal organs remain in modular runtime',()=>{for(const id of organs)assert.ok(main.includes(`['${id}'`),id)});
test('all current fixed control surfaces exist in HTML shell',()=>{for(const id of fixed)assert.ok(html.includes(`id="${id}"`),id)});
test('HTML shell boots through degraded-playable bootstrap',()=>{assert.ok(html.includes('./runtime/game-5d-bootstrap.mjs'));assert.ok(bootstrap.includes("import('./game-5d-main.mjs')"));assert.ok(bootstrap.includes('DEGRADED_PLAYABLE'));assert.equal(html.includes("joy.addEventListener('pointerdown'"),false)});
test('degraded mode keeps core movement and Y/C/Lots interactive before external 3D is ready',()=>{for(const token of ['joystickToWorld','worldHeading',"bindVertical('#yControl'","bindVertical('#lotsControl'","bindVertical('#cControl'",'requestAnimationFrame(loop)'])assert.ok(bootstrap.includes(token),token)});
test('core controls have event wiring in full game runtime',()=>{for(const token of ["joy.addEventListener('pointerdown'","$('#lookPad').addEventListener('pointerdown'","$('#attack').onclick","$('#skill').onclick","$('#dodge').onclick","$('#tradeSword').onclick","$('#flat').onclick","$('#orderFire').onclick","$('#dockToggle').onclick","$('#walletConnect').onclick","$('#walletRefresh').onclick","$('#walletToggle').onclick","bindVertical('#yControl'","bindVertical('#lotsControl'","bindVertical('#cControl'"])assert.ok(main.includes(token),token)});
test('0C walking remains independent from C control',()=>{assert.equal(main.includes('D.warp===0?0'),false);assert.ok(main.includes('function moveManual()'));assert.ok(main.includes('const speed=.10'))});
test('dynamic organ, map and object inspection actions are wired',()=>{for(const token of ['data-organ','openOrgan(','data-axis','data-market','openOrder()','closePos','setWaypoint','bindMap','inspectMapPoint','showEntityInfo'])assert.ok(main.includes(token),token)});
test('canonical coordinate runtime replaces event/canvas mirroring',()=>{assert.ok(main.includes('joystickToWorld'));assert.ok(main.includes('worldToNorthUpMap'));assert.equal(fixes.includes('scaleY(-1)'),false);assert.equal(fixes.includes('mirrorY'),false);assert.equal(fixes.includes('installMapPointerFix'),false)});
test('Y/C/Lots fixed top icons and canonical floors remain active',()=>{for(const id of ['yEnergyTap','cEnergyTap','lotsEnergyTap'])assert.ok(fixes.includes(id));assert.ok(fixes.includes('Math.floor(Math.log10(m))'));assert.ok(fixes.includes("k<0?`B${-k}`:`k=${k}`"))});
test('economy boundaries remain visibly separate',()=>{assert.ok(html.includes('KGEN Local Free'));assert.ok(html.includes('KAIOS'));assert.ok(main.includes('requiredMargin'));assert.ok(main.includes('positionRisk'));assert.ok(main.includes('playerAttack'))});
