import assert from "node:assert/strict";
import fs from "node:fs/promises";
import test from "node:test";
import { CIVILIZATION_ORDER, TERRAIN_PROFILES, UNIT_SYSTEM, createCausalWorldRuntime, createDemonstrationBranches } from "../causal-runtime/causal-world-runtime.js";

function runtime() { return createCausalWorldRuntime({ seed: "CAUSAL-TEST-001", storage: null }); }

test("uses one explicit SI-compatible unit system", () => assert.deepEqual(UNIT_SYSTEM, { distance: "meter", time: "second", mass: "kilogram", speed: "meter_per_second", energy: "joule", fuel: "liter", gravity: "meter_per_second_squared" }));
test("terrain profiles affect passability speed fuel construction wear and cost", () => {
  for (const terrain of ["PLAIN", "HILL", "MOUNTAIN", "RIVER", "WETLAND", "URBAN", "FOREST", "COAST"]) {
    for (const field of ["passable", "walking", "vehicle", "fuel", "construction", "wear", "cost"]) assert.ok(Object.hasOwn(TERRAIN_PROFILES[terrain], field));
  }
  assert.equal(TERRAIN_PROFILES.RIVER.passable, false);
});
test("valid Kaohsiung to Hsinchu route has distance time fuel wear and segments", () => {
  const route = runtime().evaluateRoute();
  assert.equal(route.blocked, false); assert.ok(route.distance_m > 300000); assert.ok(route.estimated_time_s > route.timing.travel_time_s); assert.ok(route.fuel_required_l > 0); assert.ok(route.wear_generated > 0); assert.equal(route.segments.length, 3);
});
test("river without bridge blocks route without mutating the canonical fixture", () => {
  const value = runtime();
  assert.equal(value.evaluateRoute({ no_bridge: true }).block_reason, "RIVER_WITHOUT_BRIDGE");
  assert.deepEqual(value.getSnapshot().entities.rivers[0].bridge_ids, ["BRIDGE-KH-01"]);
});
test("bridge load limit blocks overweight truck", () => assert.equal(runtime().evaluateRoute({ bridge_load_limit_kg: 15000 }).block_reason, "BRIDGE_LOAD_LIMIT"));
test("closed bridge blocks route", () => assert.equal(runtime().evaluateRoute({ bridge_closed: true }).block_reason, "BRIDGE_CLOSED"));
test("closed road blocks route", () => assert.equal(runtime().evaluateRoute({ road_closed: true }).block_reason, "ROAD_CLOSED"));
test("road load limit blocks route", () => assert.equal(runtime().evaluateRoute({ road_load_limit_kg: 15000 }).block_reason, "ROAD_LOAD_LIMIT"));
test("insufficient fuel blocks route", () => assert.equal(runtime().evaluateRoute({ fuel_level_l: 10 }).block_reason, "INSUFFICIENT_FUEL"));
test("electric transport requires recharge when energy is depleted", () => assert.equal(runtime().evaluateRoute({ electric: true, energy_level_j: 1 }).block_reason, "ENERGY_DEPLETED"));
test("electric transport consumes energy without consuming diesel", () => { const value = runtime(); value.startDelivery({ electric: true, energy_level_j: 1000000000 }); const before = value.getSnapshot().entities.vehicles[0]; value.advanceTime(3600); const after = value.getSnapshot().entities.vehicles[0]; assert.ok(after.energy_level_j < before.energy_level_j); assert.equal(after.fuel_level_l, before.fuel_level_l); });
test("electric vehicle can recharge only from simulated available energy", () => { const value = runtime(); value.startDelivery({ electric: true, energy_level_j: 500000000 }); value.pause(); const before = value.getSnapshot(); value.recharge(100000000); const after = value.getSnapshot(); assert.equal(after.entities.vehicles[0].energy_level_j, before.entities.vehicles[0].energy_level_j + 100000000); assert.equal(after.entities.energy[0].available_j, before.entities.energy[0].available_j - 100000000); });
test("route engine does not fabricate a missing path", () => assert.equal(runtime().evaluateRoute({ no_route: true }).block_reason, "NO_ROUTE"));
test("impassable terrain blocks an incompatible vehicle", () => assert.equal(runtime().evaluateRoute({ terrain_override: "RIVER" }).block_reason, "TERRAIN_NOT_PASSABLE"));
test("vehicle compatibility is enforced", () => assert.equal(runtime().evaluateRoute({ vehicle_not_compatible: true }).block_reason, "VEHICLE_NOT_COMPATIBLE"));
test("primitive civilization cannot use truck", () => assert.equal(runtime().evaluateRoute({ civilization_stage: "PRIMITIVE_FORAGING" }).block_reason, "TECHNOLOGY_NOT_AVAILABLE"));
test("canonical civilization order includes industrial gate", () => assert.ok(CIVILIZATION_ORDER.indexOf("INDUSTRIAL") > CIVILIZATION_ORDER.indexOf("AGRICULTURAL")));
test("gravity is configurable and affects fuel", () => { const value = runtime(); const earth = value.evaluateRoute().fuel_required_l; value.setGravity(3.71); assert.ok(value.evaluateRoute().fuel_required_l < earth); });
test("transport advances only by explicit time", () => { const value = runtime(); value.startDelivery(); const before = value.getSnapshot().active_delivery.remaining_s; value.advanceTime(3600); assert.equal(value.getSnapshot().active_delivery.remaining_s, before - 3600); });
test("transport work consumes Player stamina and AI energy and compute", () => { const value = runtime(); value.startDelivery(); const before = value.getSnapshot().entities.workers; value.advanceTime(3600); const after = value.getSnapshot().entities.workers; assert.ok(after[0].stamina < before[0].stamina); assert.ok(after[1].energy < before[1].energy); assert.ok(after[1].compute < before[1].compute); });
test("loading and unloading are included in total time", () => { const route = runtime().evaluateRoute(); assert.ok(route.timing.loading_time_s > 0 && route.timing.unloading_time_s > 0); });
test("wear increases and critical wear pauses delivery", () => { const value = runtime(); value.startDelivery({ vehicle_wear: 99.9 }); value.advanceTime(7200); assert.equal(value.getSnapshot().active_delivery.status, "PAUSED_MAINTENANCE"); assert.equal(value.getSnapshot().entities.vehicles[0].status, "BROKEN"); });
test("maintenance repairs and resumes from the repaired wear baseline", () => { const value = runtime(); value.startDelivery({ vehicle_wear: 99.9 }); value.advanceTime(7200); value.maintainVehicle(); value.advanceTime(3600); const state = value.getSnapshot(); assert.notEqual(state.active_delivery.status, "PAUSED_MAINTENANCE"); assert.equal(state.entities.vehicles[0].status, "IN_TRANSIT"); assert.equal(state.entities.maintenance_events.length, 1); });
test("all required entity kinds carry provenance and history", () => { const state = runtime().getSnapshot(); const records = [...state.entities.worlds, ...state.entities.regions, ...state.entities.nodes, ...state.entities.parcels, ...state.entities.roads, ...state.entities.rivers, ...state.entities.bridges, ...state.entities.vehicles, ...state.entities.cargo, ...state.entities.workers, ...state.entities.tools, ...state.entities.materials, ...state.entities.energy, ...state.entities.wear_states, state.project]; for (const item of records) { assert.ok(item.id && item.type && item.position && item.status); assert.equal(item.simulation_only, true); assert.ok(Array.isArray(item.history)); } });
test("delivery creation records canonical route and delivery-order entities", () => { const value = runtime(); value.startDelivery(); const state = value.getSnapshot(); assert.equal(state.entities.routes.at(-1).type, "ROUTE"); assert.equal(state.entities.deliveries.at(-1).type, "DELIVERY_ORDER"); });
test("missing workers blocks construction", () => { const value = runtime(); const exported = JSON.parse(value.exportState()); exported.state.entities.workers = []; value.importState(exported); assert.equal(value.advanceProject().reason, "BLOCKED_LABOR"); });
test("missing tools blocks construction", () => { const value = runtime(); const exported = JSON.parse(value.exportState()); exported.state.entities.tools = []; value.importState(exported); assert.match(value.advanceProject().reason, /BLOCKED_TOOL/); });
test("missing material blocks the matching construction stage", () => { const value = runtime(); const exported = JSON.parse(value.exportState()); exported.state.project.stage = "FOUNDATION"; exported.state.project.stage_index = 3; exported.state.inventory.STEEL = 0; value.importState(exported); assert.equal(value.advanceProject().reason, "BLOCKED_MATERIAL:STEEL"); });
test("no access route blocks construction", () => { const value = runtime(); const exported = JSON.parse(value.exportState()); exported.state.project.access_route = false; value.importState(exported); assert.equal(value.advanceProject().reason, "BLOCKED_ACCESS"); });
test("construction stages cannot skip and require time", () => { const value = runtime(); value.advanceProject(3600); assert.equal(value.getSnapshot().project.stage, "SURVEY"); value.advanceProject(3600); assert.equal(value.getSnapshot().project.stage, "SITE_CLEARING"); assert.deepEqual(value.getSnapshot().project.completed_stages, ["SURVEY"]); });
test("house foundation completes only after every ordered stage", () => { const value = runtime(); for (let index = 0; index < 30 && value.getSnapshot().project.stage !== "COMPLETE"; index += 1) value.advanceProject(21600); const state = value.getSnapshot(); assert.equal(state.project.stage, "COMPLETE"); assert.deepEqual(state.project.completed_stages, ["SURVEY", "SITE_CLEARING", "EXCAVATION", "FOUNDATION", "STRUCTURE", "UTILITIES", "INSPECTION"]); });
test("economic delivery ledger remains balanced and keeps Player and AI separate", () => { const value = runtime(); const openingTotal = Object.values(value.getSnapshot().accounts).reduce((sum, amount) => sum + amount, 0); value.startDelivery(); value.advanceTime(86400); const state = value.getSnapshot(); const closingTotal = Object.values(state.accounts).reduce((sum, amount) => sum + amount, 0); assert.ok(state.ledger.every((entry) => entry.balanced)); assert.equal(openingTotal, closingTotal); assert.equal(state.accounts.PLAYER, 72); assert.equal(state.accounts.AI, 36); assert.notEqual(state.accounts.PLAYER, state.accounts.AI); assert.ok(state.active_delivery.cost_breakdown.worker_wages > 0); assert.ok(state.active_delivery.cost_breakdown.vehicle_maintenance > 0); });
test("every causal event records state hashes", () => { const value = runtime(); value.startDelivery(); value.advanceTime(3600); assert.ok(value.getSnapshot().events.every((entry) => entry.previous_state_hash && entry.next_state_hash)); });
test("same seed and actions replay deterministically", () => { const run = () => { const value = runtime(); value.startDelivery(); value.advanceTime(3600); return value.exportState(); }; assert.equal(run(), run()); });
test("export import reset and persistence preserve boundaries", () => { const map = new Map(); const storage = { getItem: (key) => map.get(key) ?? null, setItem: (key, value) => map.set(key, value), removeItem: (key) => map.delete(key) }; const first = createCausalWorldRuntime({ storage }); first.startDelivery(); first.save(); const second = createCausalWorldRuntime({ storage }); assert.ok(second.getSnapshot().active_delivery); const exported = second.exportState(); second.reset(); assert.equal(second.getSnapshot().active_delivery, null); second.importState(exported); assert.ok(second.getSnapshot().active_delivery); });
test("unsafe import is rejected", () => { const value = runtime(); const exported = JSON.parse(value.exportState()); exported.state.real_kgen = true; assert.throws(() => value.importState(exported), /SIMULATION_BOUNDARY_VIOLATION/); });
test("five demonstration branches are deterministic", () => { const branches = createDemonstrationBranches(); assert.equal(branches.valid.blocked, false); assert.equal(branches.river.block_reason, "RIVER_WITHOUT_BRIDGE"); assert.equal(branches.bridge.block_reason, "BRIDGE_LOAD_LIMIT"); assert.equal(branches.fuel.block_reason, "INSUFFICIENT_FUEL"); assert.equal(branches.wear.status, "PAUSED_MAINTENANCE"); });
test("integrity report rejects no simulation boundary", () => assert.deepEqual(runtime().integrityReport().issues, []));
test("UI route and homepage expose causal runtime", async () => { const [home, viewer, route, app] = await Promise.all([fs.readFile(new URL("../../../index.html", import.meta.url), "utf8"), fs.readFile(new URL("../index.html", import.meta.url), "utf8"), fs.readFile(new URL("../../../world-viewer/causal-runtime/index.html", import.meta.url), "utf8"), fs.readFile(new URL("../causal-runtime/index.html", import.meta.url), "utf8")]); assert.match(home, /KAIOS 真實因果世界/); assert.match(viewer, /world-viewer\/causal-runtime/); assert.match(route, /KGEN-KAIOS\/world-viewer\/causal-runtime/); assert.match(app, /REAL CAUSAL WORLD/i); });
test("UI includes required states controls and responsive constraints", async () => { const [html, css] = await Promise.all([fs.readFile(new URL("../causal-runtime/index.html", import.meta.url), "utf8"), fs.readFile(new URL("../causal-runtime/styles.css", import.meta.url), "utf8")]); for (const id of ["loading-state", "empty-state", "error-state", "retry-button", "calculate-route", "start-simulation", "pause-simulation", "resume-simulation", "advance-time", "refuel", "recharge", "maintenance", "start-project", "export-button", "import-input", "reset-button"]) assert.match(html, new RegExp(`id="${id}"`)); assert.match(css, /@media \(max-width:\s*600px\)/); assert.match(css, /prefers-reduced-motion/); });
