import { createFishpondAquacultureRuntimeV1 } from "../../KGEN-KAIOS/world-viewer/aquaculture/aquaculture-runtime.js";

const $=(id)=>document.getElementById(id);const MAX_IMPORT_BYTES=2000000;let runtime;let view="land";
const labels={land:"Land",construction:"Pond Construction","water-source":"Water Source","water-quality":"Water Quality",fish:"Fish Population",shrimp:"Shrimp Population",feed:"Feed",oxygen:"Oxygen / Aeration",disease:"Disease Risk",mortality:"Mortality",harvest:"Harvest","cold-storage":"Cold Storage",transport:"Transport",orders:"Market Orders",inventory:"Inventory",costs:"Costs",revenue:"Revenue","cash-flow":"Cash Flow",enterprise:"Enterprise Status",events:"Event Timeline"};
const fmt=(value,digits=2)=>typeof value==="number"?Number(value).toFixed(digits):String(value??"--");
function card(title,rows,meter=null){const el=document.createElement("article");el.className="card";const h=document.createElement("h3");h.textContent=title;const dl=document.createElement("dl");for(const [key,value] of rows){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=key;dd.textContent=fmt(value);dl.append(dt,dd)}el.append(h,dl);if(meter!==null){const bar=document.createElement("div"),fill=document.createElement("span");bar.className="meter";fill.style.width=`${Math.max(0,Math.min(100,meter))}%`;bar.append(fill);el.append(bar)}return el}
function gridCards(items){const grid=document.createElement("div");grid.className="grid";for(const item of items)grid.append(item);return grid}
function render(){const state=runtime.getState(),integrity=runtime.integrityReport(),population=state.populations.reduce((sum,item)=>sum+item.count,0);$("runtime-state").textContent=state.status;$("clock").textContent=`${fmt(state.simulation_time,0)} h`;$("construction").textContent=`${state.construction.completed_stages.length} / 17`;$("water-state").textContent=state.water_quality.state;$("population").textContent=`${population} / ${state.boundaries.maximum_population}`;$("cash").textContent=fmt(state.enterprise.accounts.cash);$("integrity").textContent=integrity.ok?"INTEGRITY PASS":"INTEGRITY FAIL";$("view-title").textContent=labels[view];$("loading").hidden=true;$("error").hidden=true;const target=$("view");target.setAttribute("aria-busy","false");target.replaceChildren();let items=[];
  if(view==="land")items=[card(state.land.land_parcel_id,[["Usage right",state.land.usage_right],["Area",`${fmt(state.land.area_m2,0)} m2`],["Slope",`${fmt(state.land.slope_percent)}%`],["Soil",state.land.soil_type],["Road",state.land.road_access],["Flood risk",state.land.flood_risk]],state.land.environmental_capacity*100)];
  if(view==="construction")items=[card(state.construction.project_id,[["Stage",state.construction.stage],["Completed",state.construction.completed_stages.length],["Progress",`${fmt(state.construction.progress_hours)} h`],["Blocked",state.construction.blocked_reason??"NONE"],["Pond",state.pond.status]],state.construction.completed_stages.length/17*100),...state.construction.completed_stages.map((stage,index)=>card(`${index+1}. ${stage}`,[["Status","COMPLETE"],["Causality","TIME + INPUTS"]]))];
  if(view==="water-source")items=state.water_sources.map((source)=>card(source.type,[["ID",source.id],["Volume",`${fmt(source.volume_l,0)} L`],["Flow",`${fmt(source.flow_lph,0)} L/h`],["Reliability",source.reliability],["Rights",source.rights],["Available",source.available]],source.reliability*100));
  if(view==="water-quality")items=[card(state.water_quality.state,Object.entries(state.water_quality).filter(([key])=>key!=="last_balance").map(([key,value])=>[key,value])),card("Water Balance",state.water_quality.last_balance?Object.entries(state.water_quality.last_balance):[["Status","NO ADVANCE YET"]])];
  if(view==="fish"||view==="shrimp"){const suffix=view==="fish"?"-FISH":"-SHRIMP";items=state.populations.filter(({species_id})=>species_id.endsWith(suffix)).map((pop)=>card(pop.species_id,[["Population",pop.population_id],["Count",pop.count],["Biomass",`${fmt(pop.total_biomass_kg)} kg`],["Age",`${fmt(pop.age_hours,0)} h`],["Health",pop.health_index],["Stage",pop.growth_stage],["Status",pop.status]],pop.harvest_readiness*100))}
  if(view==="feed")items=[card("Feed Inventory",[["Status",state.feed.status],["Available",`${fmt(state.feed.inventory_kg)} kg`],["Delivered",`${fmt(state.feed.delivered_kg)} kg`],["Consumed",`${fmt(state.feed.consumed_kg)} kg`],["Waste",`${fmt(state.feed.waste_kg)} kg`],["Quality",state.feed.quality]],state.feed.quality*100)];
  if(view==="oxygen")items=[card("Pond Oxygen",[["Dissolved oxygen",`${fmt(state.water_quality.dissolved_oxygen_mg_l)} mg/L`],["Aeration",state.pond.aeration_state],["Aerator installed",state.pond.aerator_installed],["Electricity",`${fmt(state.energy.electricity_kwh)} kWh`],["Backup",`${fmt(state.energy.backup_kwh)} kWh`]],state.water_quality.dissolved_oxygen_mg_l/14*100)];
  if(view==="disease")items=state.populations.map((pop)=>card(pop.population_id,[["Status",pop.status],["Health",pop.health_index],["Stress",pop.stress_index],["Pathogen risk proxy",state.water_quality.pathogen_risk_proxy],["Certification","NONE"]],pop.health_index));
  if(view==="mortality")items=[card("Mortality / Biomass",[["Dead biomass",`${fmt(state.pond.dead_biomass_kg)} kg`],["Waste pool",`${fmt(state.pond.waste_pool_kg)} kg`],["Treatment output",`${fmt(state.pond.treatment_output_kg)} kg`],["Recorded deaths",state.populations.reduce((s,p)=>s+p.mortality_count,0)]])];
  if(view==="harvest")items=state.harvests.map((h)=>card(h.harvest_id,[["Species",h.species_id],["Count",h.count],["Gross",`${fmt(h.gross_mass_kg)} kg`],["Marketable",`${fmt(h.marketable_mass_kg)} kg`],["Rejected",`${fmt(h.rejected_mass_kg)} kg`],["Grade",h.grade],["Stage",h.stage]]));
  if(view==="cold-storage")items=state.cold_chain.map((cold)=>card(cold.delivery_id,[["Inventory",cold.inventory_id],["State",cold.state],["Temperature",`${fmt(cold.temperature_c)} C`],["Limit",`${fmt(cold.maximum_temperature_c)} C`],["Spoilage risk",cold.spoilage_risk],["Blocked",cold.blocked_reason??"NONE"]],(1-cold.spoilage_risk)*100));
  if(view==="transport")items=state.routes.map((route)=>card(route.route_id,[["Distance",`${fmt(route.distance_m/1000)} km`],["Time",`${fmt(route.estimated_time_s/3600)} h`],["Fuel",`${fmt(route.fuel_required_l)} L`],["Wear",route.wear_generated],["Blocked",route.block_reason??"NO"],["Infrastructure",route.required_infrastructure?.join(", ")??"READY"]]));
  if(view==="orders")items=state.orders.map((o)=>card(o.order_id,[["Buyer",o.buyer],["Quantity",`${fmt(o.quantity_kg)} kg`],["Grade",o.grade],["Unit price",o.unit_price],["Channel",o.channel],["Confirmed",o.confirmed],["Status",o.status]]));
  if(view==="inventory")items=state.inventory.map((item)=>card(item.inventory_id,[["Species",item.species_id],["Quantity",`${fmt(item.quantity_kg)} kg`],["Available",`${fmt(item.available_kg)} kg`],["Reserved",`${fmt(item.reserved_kg)} kg`],["Condition",item.condition],["Book value",item.book_value]]));
  if(view==="costs")items=[card("Operating Costs",[["Expenses",state.enterprise.accounts.expenses],["Payables",state.enterprise.accounts.payables],["Debt",state.enterprise.accounts.debt],["Ledger entries",state.enterprise.ledger.length]])];
  if(view==="revenue")items=[card("Recognized Revenue",[["Revenue",state.enterprise.accounts.revenue],["Rule","ACCEPTED DELIVERY ONLY"],["Receivables",state.enterprise.accounts.receivables],["Forecast recognized","NO"]])];
  if(view==="cash-flow")items=[card("Cash Flow",[["Cash",state.enterprise.accounts.cash],["Revenue",state.enterprise.accounts.revenue],["Expenses",state.enterprise.accounts.expenses],["Profit / loss",state.enterprise.profit_or_loss],["Inventory value",state.enterprise.accounts.inventory_value]])];
  if(view==="enterprise")items=[card(state.enterprise.status,[["Enterprise",state.enterprise.enterprise_id],["Currency",state.enterprise.currency],["Assets preserved",state.enterprise.assets.length],["Liabilities",state.enterprise.liabilities],["Legal effect","NONE"],["Authority",state.authority]])];
  if(view==="events"){const list=document.createElement("ol");list.className="timeline";for(const event of state.events.slice(-120).reverse()){const li=document.createElement("li"),time=document.createElement("time"),strong=document.createElement("strong"),span=document.createElement("span");time.textContent=`T${event.simulation_time}`;strong.textContent=event.event_type;span.textContent=`${event.status}${event.reason?` / ${event.reason}`:""} / ${event.next_state_hash}`;li.append(time,strong,span);list.append(li)}target.append(list);$("empty").hidden=state.events.length>0;return}
  $("empty").hidden=items.length>0;if(items.length)target.append(gridCards(items));
}
function safe(action){try{action();render()}catch(error){$("error-detail").textContent=error instanceof Error?error.message:"Unknown simulation error";$("error").hidden=false}}
function boot(){try{runtime=createFishpondAquacultureRuntimeV1();view=$("view-select").value;render()}catch(error){$("loading").hidden=true;$("error-detail").textContent=error instanceof Error?error.message:"Unknown load error";$("error").hidden=false}}
$("view-select").addEventListener("change",(event)=>{view=event.target.value;render()});
const actions={"select-land":()=>runtime.selectLand(),design:()=>runtime.designPond(),construct:()=>runtime.advanceConstruction(168),start:()=>runtime.start(),pause:()=>runtime.pause(),resume:()=>runtime.resume(),advance:()=>runtime.advanceTime(24),fill:()=>runtime.fillWater(50000),"test-water":()=>runtime.testWater(),"stock-fish":()=>runtime.stockFish(80),"stock-shrimp":()=>runtime.stockShrimp(80),"feed-action":()=>{const pop=runtime.getState().populations[0];if(pop)runtime.feed(pop.population_id,10)},aerate:()=>runtime.startAeration(4),exchange:()=>runtime.performWaterExchange(25000),health:()=>runtime.scheduleHealthCheck(),"harvest-action":()=>{const pop=runtime.getState().populations[0];if(pop)runtime.harvest(pop.population_id,40)},cold:()=>{const item=runtime.getState().inventory[0];if(item)runtime.moveToColdStorage(item.inventory_id)},market:()=>{const item=runtime.getState().inventory[0];if(item)runtime.createMarketOrder({quantity_kg:Math.max(.1,item.available_kg/2),confirmed:true})},delivery:()=>{const state=runtime.getState(),item=state.inventory[0],order=state.orders.find(({confirmed,status})=>confirmed&&status==="CONFIRMED");if(item&&order)runtime.createDeliveryOrder({inventoryId:item.inventory_id,orderId:order.order_id})},reset:()=>runtime.resetState()};
for(const [id,action] of Object.entries(actions))$(id).addEventListener("click",()=>safe(action));
$("run-scenario").addEventListener("click",()=>safe(()=>({drought:()=>runtime.runDroughtScenario(),flood:()=>runtime.runFloodScenario(),power:()=>runtime.runPowerOutageScenario(),oxygen:()=>runtime.runLowOxygenScenario(),pollution:()=>runtime.processPollution(.7),restoration:()=>runtime.processRestoration()})[$("scenario").value]()));
$("export").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(runtime.exportState(),null,2)],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="kaios-aquaculture-v1-simulation.json";link.click();URL.revokeObjectURL(link.href)});
$("import").addEventListener("change",async(event)=>{const [file]=event.target.files;if(!file)return;try{if(file.size>MAX_IMPORT_BYTES)throw new Error("匯入檔案超過 2 MB 上限。");runtime.importState(JSON.parse(await file.text()));render()}catch(error){$("error-detail").textContent=error.message;$("error").hidden=false}finally{event.target.value=""}});$("retry").addEventListener("click",boot);boot();
