from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class BootStatus(str, Enum):
    PASS = "COMPANY_BOOT_PASS"
    FAILED = "COMPANY_BOOT_FAILED"


class FailureCode(str, Enum):
    FAKE_LIFE_ID = "FAKE_LIFE_ID"
    FAKE_ATTESTATION = "FAKE_ATTESTATION"
    EXPIRED_CAPABILITY = "EXPIRED_CAPABILITY"
    REVOKED_CAPABILITY = "REVOKED_CAPABILITY"
    WRONG_MAIN_SHA = "WRONG_MAIN_SHA"
    MISSING_PARENT_HANDOFF = "MISSING_PARENT_HANDOFF"
    DUPLICATE_SESSION_ID = "DUPLICATE_SESSION_ID"
    STALE_SESSION = "STALE_SESSION"
    CURRENT_STATE_CONFLICT = "CURRENT_STATE_CONFLICT"
    SECRET_IN_OUTPUT = "SECRET_IN_OUTPUT"
    CACHE_AS_CURRENT_TRUTH = "CACHE_AS_CURRENT_TRUTH"
    UNAUTHORIZED_WORKORDER = "UNAUTHORIZED_WORKORDER"
    STATE_SHA_MISMATCH = "STATE_SHA_MISMATCH"
    HANDOFF_SHA_MISMATCH = "HANDOFF_SHA_MISMATCH"
    SESSION_LOCK_CONFLICT = "SESSION_LOCK_CONFLICT"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    BASELINE_VALIDATION_FAILED = "BASELINE_VALIDATION_FAILED"
    INVALID_JSON = "INVALID_JSON"
    MISSING_FIELD = "MISSING_FIELD"


class Stage(str, Enum):
    NEW = "NEW"
    BOOTING = "BOOTING"
    IDENTITY_VERIFIED = "IDENTITY_VERIFIED"
    CAPABILITY_VERIFIED = "CAPABILITY_VERIFIED"
    STATE_VERIFIED = "STATE_VERIFIED"
    HANDOFF_LOADED = "HANDOFF_LOADED"
    READ_ONLY_ACTIVE = "READ_ONLY_ACTIVE"
    HANDOFF_WRITTEN = "HANDOFF_WRITTEN"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"
    REVOKED = "REVOKED"
    STALE = "STALE"
    CONFLICTED = "CONFLICTED"


AUTHORIZED_ACTIONS = [
    "READ",
    "BOOT",
    "VERIFY",
    "AUDIT",
    "CREATE_SESSION_RECORD",
    "CREATE_HANDOFF_RECORD",
    "ARCHIVE_SESSION",
]

FORBIDDEN_ACTIONS = [
    "WRITE_PRODUCT_CODE",
    "MODIFY_RUNTIME_CURRENT",
    "MODIFY_UNIVERSE_MAP_CURRENT",
    "MODIFY_TOKEN",
    "CREATE_BRANCH",
    "COMMIT",
    "PUSH",
    "OPEN_PR",
    "MERGE",
    "DISPATCH_CURSOR",
    "MODIFY_WORKQUEUE",
    "SCHEDULER",
    "DEPLOY",
    "REAL_KGEN",
]

BLOCKED_ACTIONS = [
    "WRITE",
    "COMMIT",
    "PUSH",
    "PR",
    "MERGE",
    "DISPATCH",
    "DEPLOY",
]


@dataclass(frozen=True)
class BootFailure(Exception):
    code: FailureCode
    stage: Stage
    message: str
