/* KGEN_META
VERSION: 2.0.0
STATUS: ACTIVE
PURPOSE: 11520 5D game main runtime using canonical XYZ, north-up maps, inspect-before-navigation and 3D Life visuals.
*/
import * as THREE from 'three';
import {GLTFLoader} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
import {createWorldState,resolvePlayerMove,playerAttack,tickWorld,WORLD_OBJECTS} from './world-runtime.mjs';
import {createKgenLedger,requiredMargin,positionRisk,reserveOrder,activateMargin,closeMargin,snapshot} from './kgen-margin-runtime.mjs';
import {connectInjectedWallet,readNativeBalance,readErc20Balance,watchWallet} from './evm-wallet-runtime.mjs';
import {joystickToWorld,worldToNorthUpMap,northUpMapToWorld,worldHeading} from './spatial-coordinate-runtime.mjs';
import {collectInspectableEntities,inspectMapPoint,waypointSummary} from './map-object-navigation-runtime.mjs';
import {createLifeVisual,syncLifeVisual} from './life-visual-runtime.mjs';
import {install11520ProductFixes} from './game-ui-product-fixes.mjs';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KGEN='0xBA3d3810e58735cb6813bC1CDc5458C0d71432Be';
const MARKETS=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','LINKUSDT','LTCUSDT','BCHUSDT','AVAXUSDT','DOTUSDT','SUIUSDT','TONUSDT','SHIBUSDT','PEPEUSDT','UNIUSDT','NEARUSDT','AAVEUSDT'];
const ORGANS=[['world','🌍','主城世界'],['trade','⚔','K場交易'],['positions','📌','持倉'],['orders','🧾','委託'],['history','🕘','歷史'],['assets','💰','資產'],['records','📊','統計'],['market','📈','市場'],['bag','🎒','背包'],['character','🧍','角色'],['worldmap','🗺','世界地圖'],['atm','🛸','ATM'],['settings','⚙','設定'],['help','✨','客服/說明']];
const S={axis:'KX',axes:{KX:{market:'BTCUSDT',side:'多',lots:1,c:.001,pos:null},KY:{market:'ETHUSDT',side:'多',lots:1,c:.001,pos:null},KZ:{market:'BNBUSDT',side:'多',lots:1,c:.001,pos:null}},quotes:{},kaios:1000,hp:100,xyz:{x:0,y:0,z:0},heading:0,camYaw:0,joy:{sx:0,sy:0,x:0,z:0},history:[],walletKgen:null,tradeArmed:false,mapZoom:1.3,navTarget:null,navActive:false};
const ledger=createKgenLedger(100),world=createWorldState();let pending=null;
const fmt=(n,d=4)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d});
function toast(t){const el=$('#toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1700)}
function axis(){return S.axes[S.axis]}function price(){return S.quotes[axis().market]||0}

function renderAxes(){
  $('#axes').innerHTML=['KX','KY','KZ'].map(a=>{const x=S.axes[a],q=S.quotes[x.market];return `<div class="axis panel ${a===S.axis?'active':''}" data-axis="${a}"><div class="axisHead"><span>${a} 球膜軸</span><b>${q?'LIVE':'WAIT'}</b></div><select data-market="${a}">${MARKETS.map(m=>`<option ${m===x.market?'selected':''}>${m.replace('USDT','/USDT')}</option>`).join('')}</select><span class="q">${q?'$'+fmt(q,q<10?5:2):'--'}</span><span class="pos">${x.pos?`${x.pos.side} ${x.pos.lots}口 · ${x.pos.c}C`:'空倉'}</span></div>`}).join('');
  $$('[data-axis]').forEach(el=>el.onclick=e=>{if(e.target.tagName==='SELECT')return;S.axis=el.dataset.axis;syncControls();renderAxes()});
  $$('[data-market]').forEach(el=>el.onchange=e=>{const a=e.target.dataset.market;S.axes[a].market=e.target.value.replace('/','');S.axis=a;renderAxes();syncControls()});
}
async function quotes(){try{const r=await fetch('https://api.binance.com/api/v3/ticker/price',{cache:'no-store'}),j=await r.json();for(const q of j)if(MARKETS.includes(q.symbol))S.quotes[q.symbol]=+q.price;$('#feed').textContent='LIVE · Binance public'}catch{$('#feed').textContent='行情中斷'}renderAxes()}
function hud(){const s=snapshot(ledger);$('#topFree').textContent=fmt(s.free,3);$('#topKaios').textContent=fmt(S.kaios,1);$('#xyz').textContent=`X ${fmt(S.xyz.x,1)} · Y ${fmt(S.xyz.y,1)} · Z ${fmt(S.xyz.z,1)}`;$('#yRead').textContent=`Y ${fmt(S.xyz.y,1)}`;$('#hp').textContent=Math.max(0,Math.round(S.hp));$('#hpbar').style.width=Math.max(0,S.hp)+'%';$('#monsterList').innerHTML=world.monsters.filter(m=>m.state!=='DEAD'&&(m.name||m.baseName)).map(m=>`<div>${m.name||m.baseName} · ${Math.round(m.hp)}/${m.maxHp}</div>`).join('')||'<div class="muted">等待 Market Life</div>';if(S.navTarget){const w=waypointSummary(S.xyz,S.navTarget);$('#navState').textContent=`${S.navActive?'前往中':'目標'} ${w.direction} · ${fmt(w.distance,1)}m · X ${fmt(w.targetX,1)} Z ${fmt(w.targetZ,1)}`}else $('#navState').textContent='雙指縮放 · 點圖選目標'}
function setThumb(el,t){el.style.top=(100-Math.max(0,Math.min(1,t))*100)+'%'}
function syncControls(){const a=axis();$('#lotsRead').textContent=`${a.lots}口`;$('#cRead').textContent=`${a.c}C`;setThumb($('#lotsThumb'),Math.min(1,a.lots/100));const vals=[0,.000001,.00001,.0001,.001,.01,.1,10,100,1000],i=Math.max(0,vals.indexOf(a.c));setThumb($('#cThumb'),i/Math.max(1,vals.length-1));setThumb($('#yThumb'),S.xyz.y/40)}
function bindVertical(sel,fn){const el=$(sel);let pid=null;const calc=e=>{const r=el.getBoundingClientRect(),t=1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));fn(t);e.preventDefault()};el.addEventListener('pointerdown',e=>{pid=e.pointerId;el.setPointerCapture?.(pid);calc(e)});el.addEventListener('pointermove',e=>{if(e.pointerId===pid)calc(e)});['pointerup','pointercancel'].forEach(ev=>el.addEventListener(ev,e=>{if(e.pointerId===pid)pid=null}))}
bindVertical('#yControl',t=>{S.xyz.y=Math.round(t*40*10)/10;syncControls()});bindVertical('#lotsControl',t=>{axis().lots=Math.max(1,Math.round(t*100));syncControls()});bindVertical('#cControl',t=>{const vals=[0,.000001,.00001,.0001,.001,.01,.1,1,10,100,1000];axis().c=vals[Math.round(t*(vals.length-1))];syncControls()});

const joy=$('#joy'),knob=$('#knob');let joyPid=null;
function resetJoy(){S.joy.sx=0;S.joy.sy=0;S.joy.x=0;S.joy.z=0;knob.style.transform='translate(0,0)'}
function cancelNavigation(reason='手動控制'){if(S.navActive){S.navActive=false;toast(`${reason}：已停止自動導航`)}}
function joystickWorldVector(nx,screenNy){return joystickToWorld({nx,ny:-screenNy,camYaw:S.camYaw})}
function joyInput(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,dist=Math.hypot(dx,dy),travel=r.width/2*.68,k=Math.min(1,dist/travel),nx=dist?dx/dist:0,ny=dist?dy/dist:0;S.joy.sx=nx*k;S.joy.sy=ny*k;const v=joystickWorldVector(S.joy.sx,S.joy.sy);S.joy.x=v.x;S.joy.z=v.z;if(dist>4)S.heading=worldHeading(v);knob.style.transform=`translate(${nx*k*35}px,${ny*k*35}px)`;e.preventDefault()}
joy.addEventListener('pointerdown',e=>{if(e.target===knob)return;cancelNavigation();joyPid=e.pointerId;joy.setPointerCapture?.(joyPid);joyInput(e)});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyPid)joyInput(e)});['pointerup','pointercancel'].forEach(ev=>joy.addEventListener(ev,e=>{if(e.pointerId===joyPid){joyPid=null;resetJoy()}}));
let lookPid=null,lx=0;$('#lookPad').addEventListener('pointerdown',e=>{lookPid=e.pointerId;lx=e.clientX;$('#lookPad').setPointerCapture?.(lookPid)});$('#lookPad').addEventListener('pointermove',e=>{if(e.pointerId===lookPid){S.camYaw-=(e.clientX-lx)*.008;lx=e.clientX;if(Math.hypot(S.joy.sx,S.joy.sy)>.02){const v=joystickWorldVector(S.joy.sx,S.joy.sy);S.joy.x=v.x;S.joy.z=v.z;S.heading=worldHeading(v)}}});['pointerup','pointercancel'].forEach(ev=>$('#lookPad').addEventListener(ev,e=>{if(e.pointerId===lookPid)lookPid=null}));
function moveManual(){const mx=S.joy.x,mz=S.joy.z;if(Math.abs(mx)+Math.abs(mz)<.02)return;const speed=.10,r=resolvePlayerMove(S.xyz,{x:S.xyz.x+mx*speed,y:S.xyz.y,z:S.xyz.z+mz*speed});if(r.blocked){$('#collision').textContent=`BLOCKED · ${r.blocker?.name||'WORLD'}`}else{S.xyz={x:r.x,y:r.y,z:r.z};$('#collision').textContent='CLEAR'}}
function setWaypoint(x,z){S.navTarget={x,z};S.navActive=false;showWaypointAction();hud()}
function startNavigation(){if(!S.navTarget)return;S.navActive=true;$('#waypointAction')?.remove();toast('開始前往目標')}
function showWaypointAction(){document.getElementById('waypointAction')?.remove();if(!S.navTarget)return;const w=waypointSummary(S.xyz,S.navTarget),b=document.createElement('button');b.id='waypointAction';b.className='waypointAction';b.textContent=`前往 ${w.direction} · ${fmt(w.distance,1)}m`;b.onclick=startNavigation;document.body.appendChild(b)}
function moveNavigation(){if(!S.navActive||!S.navTarget)return;const dx=S.navTarget.x-S.xyz.x,dz=S.navTarget.z-S.xyz.z,d=Math.hypot(dx,dz);if(d<.35){S.navActive=false;S.navTarget=null;toast('已到達目的地');return}const ux=dx/d,uz=dz/d,step=.085;S.heading=worldHeading({x:ux,z:uz});const direct=resolvePlayerMove(S.xyz,{x:S.xyz.x+ux*step,y:S.xyz.y,z:S.xyz.z+uz*step});if(!direct.blocked){S.xyz={x:direct.x,y:direct.y,z:direct.z};$('#collision').textContent='NAV CLEAR';return}for(const p of[{x:-uz,z:ux},{x:uz,z:-ux}]){const r=resolvePlayerMove(S.xyz,{x:S.xyz.x+p.x*step,y:S.xyz.y,z:S.xyz.z+p.z*step});if(!r.blocked){S.xyz={x:r.x,y:r.y,z:r.z};S.heading=worldHeading(p);$('#collision').textContent='NAV DETOUR';return}}S.navActive=false;toast(`導航受阻：${direct.blocker?.name||'WORLD'}`)}

const MAP_RANGE=34;
function mapView(canvas){return{centerX:S.xyz.x,centerZ:S.xyz.z,range:MAP_RANGE/S.mapZoom,width:canvas.width,height:canvas.height}}
function drawMap(canvas){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,view=mapView(canvas);ctx.clearRect(0,0,w,h);ctx.fillStyle='#07151d';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#204355';for(let i=0;i<=8;i++){const x=i*w/8,y=i*h/8;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}for(const o of WORLD_OBJECTS){const p=worldToNorthUpMap(o,view);ctx.fillStyle='#9a6b35';ctx.fillRect(p.px-4,p.py-4,8,8)}for(const m of world.monsters){if(m.state==='DEAD'||!(m.name||m.baseName))continue;const p=worldToNorthUpMap(m,view);ctx.fillStyle=m.sourceManaged?'#f4d77f':'#78d4a8';ctx.beginPath();ctx.arc(p.px,p.py,4,0,Math.PI*2);ctx.fill()}if(S.navTarget){const p=worldToNorthUpMap(S.navTarget,view);ctx.strokeStyle='#68e4ff';ctx.beginPath();ctx.moveTo(w/2,h/2);ctx.lineTo(p.px,p.py);ctx.stroke();ctx.fillStyle='#68e4ff';ctx.beginPath();ctx.arc(p.px,p.py,5,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#65e798';ctx.beginPath();ctx.arc(w/2,h/2,5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(w/2,h/2);ctx.lineTo(w/2+Math.sin(S.heading)*14,h/2-Math.cos(S.heading)*14);ctx.stroke()}
function showEntityInfo(entity){$('#sheetTitle').textContent='地圖物件';$('#sheetBody').innerHTML=`<div class="card"><h3>${entity.objectName}</h3><p>OBJECT_TYPE：${entity.objectType}</p><p>LIFE_ID：${entity.lifeId||'NOT_ASSIGNED'}</p><p>X/Y/Z：${fmt(entity.x,2)} / ${fmt(entity.y,2)} / ${fmt(entity.z,2)}</p><p>功能：${entity.functionText}</p><p>互動：${entity.interactionText}</p><button class="btn" id="navToEntity">導航到這裡</button></div>`;$('#sheet').classList.add('open');$('#navToEntity').onclick=()=>{setWaypoint(entity.x,entity.z);$('#sheet').classList.remove('open')}}
function mapTap(canvas,e){const r=canvas.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*canvas.width,py=(e.clientY-r.top)/r.height*canvas.height,entities=collectInspectableEntities({objects:WORLD_OBJECTS,monsters:world.monsters}),hit=inspectMapPoint({px,py,view:mapView(canvas),entities});if(hit.kind==='ENTITY'){showEntityInfo(hit.entity);return}setWaypoint(hit.world.x,hit.world.z)}
function bindMap(canvas){const pointers=new Map();let pinchBase=null,moved=false;canvas.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture?.(e.pointerId);moved=false;if(pointers.size===2){const a=[...pointers.values()];pinchBase={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),zoom:S.mapZoom}}e.preventDefault()});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const p=pointers.get(e.pointerId);if(Math.hypot(e.clientX-p.x,e.clientY-p.y)>4)moved=true;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinchBase){const a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);S.mapZoom=Math.max(.65,Math.min(4,pinchBase.zoom*(d/pinchBase.dist)));drawAllMaps()}e.preventDefault()});const end=e=>{const wasPinch=pointers.size>1;if(!wasPinch&&!moved)mapTap(canvas,e);pointers.delete(e.pointerId);if(pointers.size<2)pinchBase=null;e.preventDefault()};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',e=>pointers.delete(e.pointerId))}
const mini=$('#minimap');bindMap(mini);let fullMapCanvas=null;function drawAllMaps(){drawMap(mini);if(fullMapCanvas&&document.body.contains(fullMapCanvas))drawMap(fullMapCanvas)}

function attackFeedback(r){if(r.ok)return r.killed?`擊殺 +${r.rewardKaios} KAIOS`:'命中生命';if(r.reason==='SOURCE_SETTLEMENT_REQUIRED')return'此 Market Life 由來源 runtime 管理，需正式市場結算';if(r.reason==='FORMAL_MARKET_SETTLEMENT_REQUIRED')return'需正式市場結算';return'生命不在攻擊距離'}
$('#attack').onclick=()=>{const r=playerAttack(world,S.xyz,{damage:35,now:Date.now()});toast(attackFeedback(r));if(r.ok&&r.killed)S.kaios+=r.rewardKaios;playAttack()};$('#skill').onclick=()=>{const r=playerAttack(world,S.xyz,{damage:60,now:Date.now()});toast(attackFeedback(r));if(r.ok&&r.killed)S.kaios+=r.rewardKaios;playAttack()};$('#dodge').onclick=()=>{cancelNavigation('閃避');const r=resolvePlayerMove(S.xyz,{x:S.xyz.x+Math.sin(S.heading)*1.4,y:S.xyz.y,z:S.xyz.z+Math.cos(S.heading)*1.4});if(!r.blocked){S.xyz={x:r.x,y:r.y,z:r.z};toast('閃避')}};$('#tradeSword').onclick=()=>{S.tradeArmed=!S.tradeArmed;toast(S.tradeArmed?'交易劍已展開':'交易劍已收合')};$('#flat').onclick=closePos;$('#orderFire').onclick=openOrder;
function openOrder(){if(!S.tradeArmed){toast('先點交易劍');return}const a=axis(),p=price();if(!p){toast('行情未就緒');return}const principal=requiredMargin({lots:a.lots}),risk=positionRisk({entry:p,mark:p,side:a.side,lots:a.lots,c:a.c});pending={axis:S.axis,market:a.market,side:a.side,lots:a.lots,c:a.c,entry:p,principal};$('#confirmBody').innerHTML=`<div class="grid2"><div class="card"><h3>${pending.axis} ${pending.market}</h3>${pending.side} · ${pending.lots}口 · ${pending.c}C<br>本金 ${pending.principal} KGEN</div><div class="card"><h3>風險</h3>每點 ±${fmt(pending.lots*pending.c,6)} KGEN<br>反向歸零 ${Number.isFinite(risk.maxAdversePoints)?fmt(risk.maxAdversePoints,3):'∞'} 點</div></div><p class="bad">目前 Confirm 只建立本機核爆部位，不送鏈。</p>`;$('#confirm').classList.add('open')}
$('#cancelOrder').onclick=$('#confirmX').onclick=()=>{pending=null;$('#confirm').classList.remove('open')};$('#confirmOrder').onclick=()=>{if(!pending)return;const a=S.axes[pending.axis];if(a.pos){toast('此軸已有持倉');return}const r=reserveOrder(ledger,pending.principal);if(!r.ok){toast('KGEN Free 不足');return}activateMargin(ledger,pending.principal);a.pos={...pending};S.history.unshift({time:new Date().toLocaleTimeString(),axis:pending.axis,event:'開倉'});pending=null;$('#confirm').classList.remove('open');toast('本機核爆成交');renderAxes();hud()};
function closePos(){const a=axis(),p=a.pos;if(!p){toast(`${S.axis} 空倉`);return}const mark=price()||p.entry,r=positionRisk({...p,mark});closeMargin(ledger,{margin:p.principal,pnl:r.pnl});a.pos=null;toast(`平倉 ${fmt(r.pnl,4)} KGEN`);renderAxes();hud()}

const dock=$('#dock');$('#dockToggle').onclick=()=>dock.classList.toggle('open');$('#rail').innerHTML=ORGANS.map(([id,ic,n])=>`<button data-organ="${id}" title="${n}">${ic}</button>`).join('');$$('[data-organ]').forEach(b=>b.onclick=()=>openOrgan(b.dataset.organ));$('#sheetClose').onclick=()=>{$('#sheet').classList.remove('open');fullMapCanvas=null};
function openOrgan(id){$('#sheetTitle').textContent=ORGANS.find(x=>x[0]===id)?.[2]||id;const s=snapshot(ledger);let h='';if(id==='trade')h=`<div class="card"><h3>${S.axis} ${axis().market}</h3><button id="sideBtn" class="btn">方向：${axis().side}</button><p>口數 ${axis().lots}｜C ${axis().c}</p><p>本金 = 口數 × 1 KGEN</p></div>`;else if(id==='positions')h=['KX','KY','KZ'].map(a=>`<div class="card">${a}：${S.axes[a].pos?`${S.axes[a].pos.side} ${S.axes[a].pos.lots}口 ${S.axes[a].pos.c}C`:'空倉'}</div>`).join('');else if(id==='assets')h=`<div class="card">KGEN Local Free ${fmt(s.free,3)}<br>Locked ${fmt(s.lockedMargin,3)}<br>Verified Wallet ${S.walletKgen==null?'未連線':fmt(S.walletKgen,6)}</div>`;else if(id==='history')h=S.history.map(x=>`<div class="card">${x.time} · ${x.axis} · ${x.event}</div>`).join('')||'尚無歷史';else if(id==='character')h=`<div class="card">HP ${S.hp}/100<br>3D：${$('#charState').textContent}<br>世界座標：X ${fmt(S.xyz.x,1)} / Y ${fmt(S.xyz.y,1)} / Z ${fmt(S.xyz.z,1)}<br>Z+ = 北，X+ = 東。</div>`;else if(id==='worldmap')h='<div class="mapHint">NORTH_UP。單點空白處先設定 waypoint；點建築/生命先看資料，再選導航。雙指縮放；手動碰左下 XZ 遙桿會停止自動導航。</div><div class="mapStage"><canvas id="fullMap" width="900" height="700"></canvas></div>';else if(id==='help')h='<div class="card"><h3>操作說明</h3>左下 XZ 遙桿採鏡頭相對 360° 向量；Z+ 是北、X+ 是東。遙桿中央單擊等待 1 秒 Y+，雙擊等待 1 秒 Y−。地圖點物件會先顯示名稱、類型、LIFE_ID 與 XYZ，不會直接瞬移。</div>';else h=`<div class="card">${ORGANS.find(x=>x[0]===id)?.[2]||id} 器官已啟用。</div>`;$('#sheetBody').innerHTML=h;$('#sheet').classList.add('open');dock.classList.remove('open');$('#sideBtn')?.addEventListener('click',()=>{axis().side=axis().side==='多'?'空':'多';openOrgan('trade')});if(id==='worldmap'){fullMapCanvas=$('#fullMap');bindMap(fullMapCanvas);drawMap(fullMapCanvas)}}

const wallet={provider:null,account:null};async function refreshWallet(){if(!wallet.provider||!wallet.account)return;try{const [n,t]=await Promise.all([readNativeBalance({provider:wallet.provider,account:wallet.account}),readErc20Balance({provider:wallet.provider,token:KGEN,account:wallet.account,decimals:18})]);$('#wBnb').textContent=fmt(n.formatted,6);S.walletKgen=t.ok?Number(t.formatted):null;$('#wKgen').textContent=t.ok?fmt(t.formatted,6):'--';$('#walletMsg').textContent='已連線｜鏈上餘額唯讀｜不自動送交易'}catch{$('#walletMsg').textContent='錢包讀取失敗'}}$('#walletConnect').onclick=async()=>{const w=await connectInjectedWallet({allowedChainIds:[56]});if(!w.ok){$('#walletMsg').textContent=w.reason==='NO_INJECTED_WALLET'?'此瀏覽器沒有注入式 EVM 錢包':'錢包/鏈不符合 BSC 56';$('#walletPanel').classList.remove('collapsed');return}wallet.provider=w.provider;wallet.account=w.account;$('#wAddr').textContent=w.account.slice(0,6)+'…'+w.account.slice(-4);$('#wChain').textContent=w.chainId;walletUnwatch=watchWallet({provider:w.provider,onAccountsChanged:()=>location.reload(),onChainChanged:()=>location.reload()});$('#walletPanel').classList.remove('collapsed');await refreshWallet()};$('#walletRefresh').onclick=refreshWallet;$('#walletToggle').onclick=()=>$('#walletPanel').classList.toggle('collapsed');let walletUnwatch=()=>{};

const scene=new THREE.Scene();scene.background=new THREE.Color(0x08110d);scene.fog=new THREE.FogExp2(0x08110d,.025);const camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,500),renderer=new THREE.WebGLRenderer({canvas:$('#three'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));scene.add(new THREE.HemisphereLight(0xddeeff,0x223311,2.5));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(5,12,6);scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(120,120),new THREE.MeshStandardMaterial({color:0x294f2d}));ground.rotation.x=-Math.PI/2;scene.add(ground);
for(let i=0;i<28;i++){const g=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.12,.18,1.2,8),new THREE.MeshStandardMaterial({color:0x5c3920})),leaf=new THREE.Mesh(new THREE.ConeGeometry(.55,1.4,8),new THREE.MeshStandardMaterial({color:0x1e6b32}));tr.position.y=.6;leaf.position.y=1.7;g.add(tr,leaf);g.position.set((Math.random()-.5)*45,0,(Math.random()-.5)*45);scene.add(g)}
for(const o of WORLD_OBJECTS){let mesh;if(o.kind==='ATM'){mesh=new THREE.Mesh(new THREE.SphereGeometry(.85,20,12),new THREE.MeshStandardMaterial({color:0x8fb9cf,metalness:.65,roughness:.3}));mesh.scale.y=.42;mesh.position.set(o.x,1.1,o.z)}else{mesh=new THREE.Mesh(new THREE.BoxGeometry(o.halfX*1.4,2.4,o.halfZ*1.4),new THREE.MeshStandardMaterial({color:o.kind==='SHOP'?0x806236:0x76563f}));mesh.position.set(o.x,1.2,o.z)}mesh.userData={worldObjectId:o.id,lifeId:o.lifeId};scene.add(mesh)}
const avatar=new THREE.Group();scene.add(avatar);let mixer=null,actions={},current='';const fallback=()=>{const b=new THREE.Mesh(new THREE.CapsuleGeometry(.25,.78,4,8),new THREE.MeshStandardMaterial({color:0x2f4050}));b.position.y=.72;avatar.add(b);$('#charState').textContent='PRIMITIVE FALLBACK'};function pick(rx){return Object.keys(actions).find(n=>rx.test(n))}function play(kind){if(!mixer)return;const n=kind==='walk'?pick(/walk|run/i):kind==='attack'?pick(/attack|slash|sword/i):pick(/idle/i);if(!n||n===current)return;actions[current]?.fadeOut(.12);actions[n].reset().fadeIn(.12).play();current=n}function playAttack(){play('attack');setTimeout(()=>play('idle'),400)}new GLTFLoader().load('https://raw.githubusercontent.com/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0/main/addons/kaykit_character_pack_adventures/Characters/gltf/Knight.glb',g=>{g.scene.scale.setScalar(.50);avatar.add(g.scene);mixer=new THREE.AnimationMixer(g.scene);g.animations.forEach(c=>actions[c.name]=mixer.clipAction(c));$('#charState').textContent='Knight 3D READY';play('idle')},undefined,()=>fallback());
const lifeVisuals=new Map(),lifeVisualPending=new Set();async function ensureLifeVisual(m){if(m.state==='DEAD'||!(m.name||m.baseName))return null;const key=`${m.lifeId||m.id}|${m.species}`;const current=lifeVisuals.get(m.id);if(current?.key===key)return current.root;if(current){scene.remove(current.root);lifeVisuals.delete(m.id)}if(lifeVisualPending.has(m.id))return null;lifeVisualPending.add(m.id);try{const v=await createLifeVisual(THREE,{species:m.species,name:m.baseName||m.name,scale:.75});scene.add(v.root);lifeVisuals.set(m.id,{key,root:v.root,mode:v.mode});return v.root}finally{lifeVisualPending.delete(m.id)}}
function syncLifeVisuals(){for(const m of world.monsters){const rec=lifeVisuals.get(m.id);if(m.state==='DEAD'||!(m.name||m.baseName)){if(rec)rec.root.visible=false;continue}if(!rec){void ensureLifeVisual(m);continue}const key=`${m.lifeId||m.id}|${m.species}`;if(rec.key!==key){void ensureLifeVisual(m);continue}syncLifeVisual(rec.root,m)}}
function resize(){renderer.setSize(innerWidth,innerHeight,true);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,(now-last)/1000);last=now;mixer?.update(dt);if(S.navActive)moveNavigation();else moveManual();avatar.position.set(S.xyz.x,S.xyz.y,S.xyz.z);avatar.rotation.y=S.heading;play((S.navActive||Math.abs(S.joy.x)+Math.abs(S.joy.z)>.05)?'walk':'idle');const tr=tickWorld(world,S.xyz,Date.now());for(const e of tr.events)if(e.type==='PLAYER_HIT')S.hp=Math.max(0,S.hp-e.damage);syncLifeVisuals();const dist=8.5;camera.position.set(S.xyz.x+Math.sin(S.camYaw)*dist,S.xyz.y+4.2,S.xyz.z-Math.cos(S.camYaw)*dist);camera.lookAt(S.xyz.x,S.xyz.y+.8,S.xyz.z);hud();drawAllMaps();renderer.render(scene,camera)}

renderAxes();syncControls();quotes();setInterval(quotes,5000);install11520ProductFixes();requestAnimationFrame(frame);$('#charState').textContent='3D LOADING';toast('11520 canonical runtime 已啟動');
